server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: High Score IO

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          time_zone=UTC

  datasource:
    url: ${RDS_URL}
    driver-class-name: org.postgresql.Driver
    username: ${RDS_UN}
    password: ${RDS_PASS}

  aop:
    auto: true
    proxy-target-class: true

  jackson:
    serialization:
      fail-on-empty-beans: false

